// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repo

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	DeleteProduct(ctx context.Context, id int64) error
	FindProductByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
